import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const tokenPath = path.join(root, "tokens", "cimbyte.tokens.json");
const cssPath = path.join(root, "cimbyte.css");
const androidPath = path.join(
  root,
  "android",
  "cimbyte-ui-compose",
  "src",
  "main",
  "kotlin",
  "ro",
  "cimbyte",
  "ui",
  "GeneratedCimbyteTokens.kt",
);
const check = process.argv.includes("--check");
const begin = "/* BEGIN GENERATED TOKENS — run npm run generate */";
const end = "/* END GENERATED TOKENS */";

const tokens = JSON.parse(await readFile(tokenPath, "utf8"));

function cssDeclarations(theme) {
  return Object.values(theme.colors).map(({ cssName, css }) => `  --cb-${cssName}: ${css};`);
}

function generatedCss() {
  const dark = tokens.themes.dark;
  const light = tokens.themes.light;
  const shared = [
    ...Object.entries(tokens.cssVariables).map(([name, value]) => `  --cb-${name}: ${value};`),
    ...cssDeclarations(dark),
    `  --cb-sans: ${tokens.fonts.sans.css};`,
    `  --cb-mono: ${tokens.fonts.mono.css};`,
    ...Object.entries(tokens.dimensions).map(([name, value]) => `  --cb-${name}: ${value.css};`),
    ...Object.entries(tokens.shadows).map(([name, value]) => `  --cb-${name}: ${value};`),
  ];
  return `${begin}
:root {
  color-scheme: ${dark.colorScheme};
${shared.join("\n")}
}

[data-cb-theme="light"] {
  color-scheme: ${light.colorScheme};
${cssDeclarations(light).join("\n")}
}
${end}`;
}

function composeProperties(theme) {
  return Object.values(theme.colors)
    .filter((color) => color.composeName)
    .map((color) => `    val ${color.composeName} = Color(0x${color.androidArgb})`)
    .join("\n");
}

function generatedKotlin() {
  const dimensions = Object.values(tokens.dimensions)
    .filter((dimension) => dimension.composeName)
    .map((dimension) => `    val ${dimension.composeName} = ${dimension.androidDp}.dp`)
    .join("\n");
  return `// Generated by scripts/generate-tokens.mjs. Do not edit directly.
package ro.cimbyte.ui

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

internal object CimbyteDarkColorTokens {
${composeProperties(tokens.themes.dark)}
}

internal object CimbyteLightColorTokens {
${composeProperties(tokens.themes.light)}
}

internal object CimbyteDefaultDimensions {
${dimensions}
}
`;
}

async function update(filePath, next) {
  const current = await readFile(filePath, "utf8").catch(() => "");
  if (current === next) return false;
  if (check) throw new Error(`${path.relative(root, filePath)} is not generated from ${path.relative(root, tokenPath)}`);
  await writeFile(filePath, next);
  return true;
}

const css = await readFile(cssPath, "utf8");
const start = css.indexOf(begin);
const finish = css.indexOf(end);
if (start === -1 || finish === -1 || finish < start) {
  throw new Error(`Missing generated token markers in ${path.relative(root, cssPath)}`);
}
const nextCss = `${css.slice(0, start)}${generatedCss()}${css.slice(finish + end.length)}`;
const changed = [];
if (await update(cssPath, nextCss)) changed.push(path.relative(root, cssPath));
if (await update(androidPath, generatedKotlin())) changed.push(path.relative(root, androidPath));
if (!check && changed.length) process.stdout.write(`Generated ${changed.join(", ")}\n`);
