// Generated by scripts/generate-tokens.mjs. Do not edit directly.
package ro.cimbyte.ui

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

internal object CimbyteDarkColorTokens {
    val accent = Color(0xFFDD503F)
    val onAccent = Color(0xFFFFFFFF)
    val accentSoft = Color(0xFF421C16)
    val background = Color(0xFF0E1218)
    val backgroundSecondary = Color(0xFF14181F)
    val backgroundTertiary = Color(0xFF1D2229)
    val surface = Color(0xFF171B22)
    val textPrimary = Color(0xFFECEFF2)
    val textSecondary = Color(0xFFCBCED1)
    val textMuted = Color(0xFF7D8086)
    val border = Color(0xFF303338)
    val borderSoft = Color(0xFF24272B)
    val error = Color(0xFFDE3B3D)
    val errorSoft = Color(0x1ADE3B3D)
    val success = Color(0xFF11AD32)
    val successSoft = Color(0x1A11AD32)
    val warning = Color(0xFFDFA11A)
    val warningSoft = Color(0x1FDFA11A)
    val info = Color(0xFF2696E4)
    val infoSoft = Color(0x1F2696E4)
}

internal object CimbyteLightColorTokens {
    val accent = Color(0xFFDD503F)
    val onAccent = Color(0xFFFFFFFF)
    val accentSoft = Color(0xFFFFDCD4)
    val background = Color(0xFFF7F8FA)
    val backgroundSecondary = Color(0xFFF0F2F4)
    val backgroundTertiary = Color(0xFFE6E8EB)
    val surface = Color(0xFFFFFFFF)
    val textPrimary = Color(0xFF181B1F)
    val textSecondary = Color(0xFF303338)
    val textMuted = Color(0xFF6E7278)
    val border = Color(0xFFD5D8DB)
    val borderSoft = Color(0xFFE3E5E8)
    val error = Color(0xFFCC272E)
    val errorSoft = Color(0x14CC272E)
    val success = Color(0xFF00801A)
    val successSoft = Color(0x1400801A)
    val warning = Color(0xFFA86D00)
    val warningSoft = Color(0x17A86D00)
    val info = Color(0xFF0077C2)
    val infoSoft = Color(0x140077C2)
}

internal object CimbyteDefaultDimensions {
    val radiusSmall = 8.dp
    val radiusMedium = 10.dp
    val radiusLarge = 14.dp
    val radiusExtraLarge = 16.dp
    val radiusPill = 999.dp
    val spacingExtraSmall = 4.dp
    val spacingSmall = 8.dp
    val spacingMedium = 12.dp
    val spacingLarge = 16.dp
    val spacingExtraLarge = 24.dp
    val controlHeightSmall = 32.dp
    val controlHeightMedium = 40.dp
    val controlHeightLarge = 48.dp
}
